#!/bin/bash

while true; do
	
	fsz=3500;  # The max file size of a .cow file for it to be used
	timeout=20; # Time until the script refreshes

	# Find a cow file less than the threashold in bytes
	cow=$(find ./cowsay-files/cows -size "-${fsz}c" | grep "\.cow$" | shuf -n 1)
	cow_size=$(wc -c < "$cow");

	sleep 0
	
	    clear;
	    ./now; # Call the neighboring ./now script to display weather/date/time
	    fortune -n 500 | cowsay -f "$cow";
	    echo "Using ""$(basename $cow) - ${cow_size}B";
	    # Countdown loop
	    count=$timeout;
	    while (( count >= 0 )); do
	        echo -en "  ${count}s remaining\r";
	        ((count--));
	        sleep 1;
	    done;
	
	    # Sleep for 1 second before refreshing
	    sleep 1.0;
done;
